language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install .
  - pip install python-coveralls
script:
  - pylint -E persephone
  - mypy persephone
  - pytest
notifications:
  email:
    recipients:
      - oliver.adams@gmail.com
after_success:
  - coveralls
